name: Deploy Lab
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t Fileuploadlab .
    - name: Run Docker container
      run: |
        docker run -d -p 8080:80 Fileuploadlab
        sleep 5
        
    - name: Open localtunnel
      run: |
        lt --port 8080 
